name: torchiva
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision
  - torchaudio
  - tensorboard
  - numpy
  - scipy>=1.5.0
  - sox
  - pip
  - pip:
      - pytorch-lightning>=1.0.0
      - pyroomacoustics
      - nussl
      - nara_wpe
      - PyYAML
